name: Create Bin Branch

on:
  push:
    branches:
      - master  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          npm i -g pnpm
          pnpm install
          pnpm run build

      - name: List remaining files
        run: ls -la

      - name: Delete all files except the bin directory
        run: rm -r $(ls -A | grep -vE '^(.git|dist)$')

      - name: List remaining files
        run: mv dist/* .

      - name: Create a branch with the dir
        run: |
          git checkout prod
          git add .
          git commit -m "pushing in prod"
          git push
