name: Create Bin Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: List remaining files
        run: ls -la

      - name: Move build artifacts to bin directory
        run: mv dist/* bin/

      - name: Set up Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github"

      - name: Create prod branch if it doesn't exist
        run: |
          git checkout -B prod

      - name: Add changes to git
        run: git add .

      - name: Commit changes
        run: git commit -m "Push build artifacts to prod branch"

      - name: Push changes to prod branch
        run: git push origin prod
